### PR TITLE
 +init examples for creating new user

### PR DESCRIPTION
**Pull request by gabrielhesposito**
I had to get twister core running first - thankfully easy
https://github.com/miguelfreitas/twister-core/pull/440

after going through testing  I found that despite having implemented a `createrawtransaction` function via `generateClientSideAccount` no user is created.

this PR aims to :

implement a function for `createwalletuser`
example request:
```
{"jsonrpc":"2.0","method":"createwalletuser","params":["username"],"id":1}
```
response
```
{"result":"privkey","error":null,"id":1}
```

implement a function for `sendnewusertransaction`
```
{"jsonrpc":"2.0","method":"sendnewusertransaction","params":["newusername"],"id":1}
```

also document w/ examples

**12/23**

these functions now check if the user name is available, create the user in the wallet and publish it to the network.

example executions + rpc requests made;

```
root@7f2b0ae4bd23:/opt/node/twister-lib-js/examples# node 023_create_new_account.js &&   node 024_pub
lish_new_account.js
{"jsonrpc": "2.0", "method": "dumppubkey", "params": ["bugativendor4u"], "id": 0}
{"jsonrpc": "2.0", "method": "createwalletuser", "params": ["bugativendor4u"], "id": 0}
your priv key : <redacted>
{"jsonrpc": "2.0", "method": "sendnewusertransaction", "params": ["bugativendor4u"], "id": 0}
```

#### note:

the `RPC` function will return the http status 500, 404 etc but it does not return the specific error message from `twister-core`  like below

```
ERROR: CheckUsername() : username size out of limits
ERROR: CheckTransaction() : username check failed
ERROR: CTxMemPool::accept() : CheckTransaction failed
```

I don't know if it still needs to be implemented in this lib or `twister-core`, but capturing  the specific error message would be nice to have. 

## 12/25

I moved the functions in to the `server` directory since the create/send rpc are only necessary when creating a user via the server.  these functions are intended to comprise the "server" implementation.

after reviewing the existing implementation I believe `.generateClientSideAccount` is accurately handling user creation on the client side, the private key is generated client side.

```
lib-js/examples# node 023_create_new_account_client.js
raw transaction:  01000000000f0e62756761746973616c76616765332221037549900d7347bff67d9ee3591a4623cc59ee1a3e81fe233988664637e9c378cc6b0ebb00
sent transaction 0000001fccb0512856753637841c8a5cca1870597011e205923770d9478ded31
your priv key : <redacted>
```

#### note:
timeout had to be bumped
```
root@164faa63fcd2:/opt/lib-js/examples# node 023_create_new_account_client.js
Twister error: Host not reachable.
```

#### testing generateClientSideAccount
run the example
```
# node 023_create_new_account_client.js 
your pubkey 0367851078ca430bd32de71af75575d5eb50e9c30cdbc759cc6d2d161466b88447
raw transaction:  01000000000908676573706f31303022210367851078ca430bd32de71af75575d5eb50e9c30cdbc759cc6d2d161466b88447f1093600
sent transaction 000000ccb17a0daf9a0434a4f79b551c99e27ff04bc45291717bfc3f50aa7c22
your priv key : <redacted>
```

import wont work immediately
wait
after a few minutes 
login

### CODE REVIEW

**Comment by gabrielhesposito** [comment]
this is for https://github.com/Tschaul/twister-lib-js/issues/5
will change from WIP once init functions are pushed

**Comment by gabrielhesposito** [comment]
ok I have initial user creation working on client side;

```
root@7f2b0ae4bd23:/opt/node/twister-lib-js/examples# node 023_create_new_account.js
Twister error: Request was not processed successfully (http error: 500).
root@7f2b0ae4bd23:/opt/node/twister-lib-js/examples# node 023_create_new_account.js
user created in walletL33RztJH74QpFHEL1U....
root@7f2b0ae4bd23:/opt/node/twister-lib-js/examples#
```

next I'm to going to restructure  the code into `src/ClientWallet` and implement the network side into `src/ServerWallet`

**Comment by gabrielhesposito** [comment]
this is ready for review - feedback welcomed

**Comment by Tschaul** [comment]
Hey Gabriel,

Thanks a lot for your efforts! However, the 'createwalletuser' json-rpc command you are using creates a new user at the server with a new private key, hence it leaks the private key. This would be a suitable implemenation for the ServerWallet directoy. The ClientWallet is all about not leaking the private key. Hence you need to send the raw binary transaction to the json rpc command 'sendrawtransaction' because it contains a signature using the private key. For that you have to reimplement the corresponding code in twister-core. Maybe some bitcoin libraries can help you with that. You will however need a thorough understanding of both the bitcoin and the twister blockchain and quite a bit of crypto knowledge in general. Kudos if you can do it!

Merry Christmas!

**Comment by gabrielhesposito** [comment]
@Tschaul  much thanks for the review. merry Christmas :) .
I understand the distinction between client/server better after your explanation.

I now believe the client side is already implemented with `generateClientSideAccount`. 
I'll capture the output and manually confirm it .

**Comment by centaur1** [comment]
Hi,
I haven't had a chance to test it yet, has anyone else tried it?

**Comment by gabrielhesposito** [comment]
hey @centaur1 I just tested `generateClientSideAccount`, AFICT it works. - I put some screen shots above.
I've also tested the server side examples.

**Comment by centaur1** [comment]
Hi,
If @Tschaul is okay with it, I am.  
Thanks!

**Comment by gabrielhesposito** [comment]
@Tschaul can you help us confirm/deny if the existing `generateClientSideAccount` represents the adequate client wallet application ? much thanks!

**Comment by Tschaul** [comment]
yes, i had a look and indeed it seams like miguel built this endpoint that creates the raw transaction. Totally forgot about that. This one does not leak the private key and hence its the correct behavior for the client side wallet.

Btw are you using the library in the twister-html? Kudos!!

**Comment by gabrielhesposito** [comment]
much thanks @Tschaul , yes I gave it go with node and twister-react. looks like both twister-react/twister-html
hopefully the project picks up more traction. maybe a free node channel is need

**Pull request merged**
